In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [27]:
df = pd.read_csv(r'C:\Users\Junaid\Desktop\crop\Crop_recommendation.csv')

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [41]:
df.head(3)

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice

In [42]:
x=df[['N','P','K','temperature','humidity','ph','rainfall']]

In [44]:
y=df['label']

In [46]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [47]:
x_train

       N    P    K  temperature   humidity        ph    rainfall
1607   0   18   14    29.771494  92.007200  7.207991  114.416179
1212   9  122  201    29.587484  80.919344  5.570291   68.064173
362   11   71   24    21.140114  22.718235  5.606620  141.605672
566   38   38   18    26.310518  61.187491  6.294130   35.734038
1671  18   12    8    12.590940  91.816688  6.206053  119.391672
...   ..  ...  ...          ...        ...       ...         ...
808   13   64   20    19.134577  62.575269  6.590571   36.469470
422   16   55   19    19.543141  47.191883  6.413544  192.437219
2052  82   48   36    25.793520  81.769040  6.352077  193.241838
2083  90   50   44    26.916437  73.486560  6.253409  171.471638
1282   1  132  200    16.278528  82.942701  5.620746   66.574628

[1760 rows x 7 columns]

In [48]:
y_train

1607         orange
1212         grapes
362     kidneybeans
566       mothbeans
1671         orange
           ...
808          lentil
422      pigeonpeas
2052           jute
2083           jute
1282         grapes
Name: label, Length: 1760, dtype: object

In [53]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [58]:
x_train_scaled_df=pd.DataFrame(x_train_scaled,columns=x_train.columns)

In [ ]:
x_train_scaled_df

In [65]:
models={
    "Random Forest":RandomForestClassifier(n_estimators=200,random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN":KNeighborsClassifier(n_neighbors=5),
    "Logistic Regression": LogisticRegression(max_iter=200,random_state=42),
    "SVM(RBF Kernel)":SVC(kernel='rbf',random_state=42)
}

results=[]
for name,model in models.items():
    if name in ["KNN","Decision Tree","Logistic Regression","SVM(RBF Kernel)"]:
        model.fit(x_train_scaled,y_train)
        preds=model.predict(x_test_scaled)
    else:
        model.fit(x_train,y_train)
        preds=model.predict(x_test)

    acc=accuracy_score(y_test,preds)
    results.append((name,acc))

In [69]:
results

[('Random Forest', 0.9954545454545455),
 ('Decision Tree', 0.9795454545454545),
 ('KNN', 0.9795454545454545),
 ('Logistic Regression', 0.9727272727272728),
 ('SVM(RBF Kernel)', 0.9840909090909091)]

In [71]:
results_df=pd.DataFrame(results,columns=["Model","Accuracy"])
results_df

                 Model  Accuracy
0        Random Forest  0.995455
1        Decision Tree  0.979545
2                  KNN  0.979545
3  Logistic Regression  0.972727
4      SVM(RBF Kernel)  0.984091

In [73]:
results_df=results_df.sort_values(by="Accuracy",ascending=False)
results_df

                 Model  Accuracy
0        Random Forest  0.995455
4      SVM(RBF Kernel)  0.984091
1        Decision Tree  0.979545
2                  KNN  0.979545
3  Logistic Regression  0.972727

In [74]:
import pickle as pkl

In [77]:
best_model = RandomForestClassifier(n_estimators=200,random_state=42)
best_model.fit(x_train,y_train)
preds=best_model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("Best Model Accuracy:",acc)

Best Model Accuracy: 0.9954545454545455

In [79]:
bundle={
    "model":best_model,
    "feature_cols":['N','P','K','temperature','humidity','ph','rainfall'],
    "classes":best_model.classes_
}

In [81]:
with open('Crop_recommendation_RF.pkl','wb') as f:
    pkl.dump(bundle,f)
    print("Model Saved Succesfully")

Model Saved Succesfully

In [82]:
with open('Crop_recommendation_RF.pkl','rb') as f:
    b=pkl.load(f)
    print(b["model"])

RandomForestClassifier(n_estimators=200, random_state=42)

In [87]:
sample={'N':90,'P':40,'K':40,'temperature':20,'humidity':80,'ph':7,'rainfall':200}
x=[[sample[c] for c in b["feature_cols"]]]
x

[[90, 40, 40, 20, 80, 7, 200]]

In [89]:
print("predict" ,b["model"].predict(x)[0])

predict rice

C:\Users\Junaid\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(